# Generated by Django 2.1 on 2019-12-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20191201_0640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('price_int',)},
        ),
    ]
